site_name: Your dbt Models
# site_url: http://catalogs.unytics.io/bigquery_public_data/
extra_css:
  - style.css
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    # - navigation.tabs
    - navigation.prune
    - navigation.indexes
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins: []