SELECT 
    DATABASE_NAME, 
    DATABASE_OWNER, 
    IS_TRANSIENT,
    COMMENT AS DATABASE_COMMENT, 
    CREATED AS DATABASE_CREATION, 
    RETENTION_TIME, 
    TYPE AS DATABASE_TYPE
FROM INFORMATION_SCHEMA.DATABASES;