SELECT 
    CATALOG_NAME AS DATABASE_NAME,
    SCHEMA_NAME,
    SCHEMA_OWNER,
    IS_TRANSIENT,
    IS_MANAGED_ACCESS,
    RETENTION_TIME,
    CREATED AS SCHEMA_CREATION,
    COMMENT AS SCHEMA_COMMENT
FROM INFORMATION_SCHEMA.SCHEMATA;