SELECT 
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_OWNER,
    TABLE_TYPE,
    IS_TRANSIENT,
    CLUSTERING_KEY,
    ROW_COUNT,
    BYTES,
    RETENTION_TIME,
    CREATED AS TABLE_CREATION,
    LAST_ALTERED AS LAST_MODIFICATION,
    LAST_DDL AS LAST_STRUCTURE_CHANGE,
    LAST_DDL_BY AS LAST_STRUCTURE_CHANGER,
    COMMENT AS TABLE_COMMENT,
    IS_TEMPORARY
FROM INFORMATION_SCHEMA.TABLES;